name: dbt_covid

profile: dbt_covid

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_covid:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
      +schema: staging
    bronze:
      +materialized: table
      +schema: bronze
    # Silver layer - cleaned, conformed
    silver:
      +materialized: table
      +schema: silver
    # Gold layer - business ready aggregates
    gold:
      +materialized: table
      +schema: gold